import { describe, expect, it } from 'vitest';
import { parseYarnLockfile } from '../../src/services/analysis/lockfiles/yarnLockfileParser.js';

const SAMPLE_YARN_LOCK = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4/GHRvSCoTsjjmY7wDwtCT+2ZgOu9U2ipC7VJPQiUJK4iy86kUEV2E6dV4bAA==

"@babel/core@^7.20.0":
  version "7.20.5"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.20.5.tgz#s"
  integrity sha512-abc
  dependencies:
    lodash "^4.17.19"
`;

describe('parseYarnLockfile', () => {
  it('parses entries including scoped packages and their dependencies', () => {
    const lockfile = parseYarnLockfile(SAMPLE_YARN_LOCK);

    expect(lockfile.kind).toBe('yarn');
    const lodash = lockfile.packages.find((p) => p.name === 'lodash');
    expect(lodash?.version).toBe('4.17.21');

    const babelCore = lockfile.packages.find((p) => p.name === '@babel/core');
    expect(babelCore?.version).toBe('7.20.5');
    expect(babelCore?.dependencies).toEqual({ lodash: '^4.17.19' });
  });

  it('throws a clean error on unparseable content', () => {
    expect(() => parseYarnLockfile('<<<<<<< HEAD\nbroken\n=======\n>>>>>>> branch')).toThrow(/Invalid yarn\.lock/);
  });
});
